# Generated by Django 5.0.6 on 2024-07-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vote_user_is_admin_alter_user_id_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.CharField(choices=[('ENTERTAINMENT', 'Entretenimento'), ('TECHNOLOGY', 'Tecnologia'), ('SPORTS', 'Esportes'), ('FOOD', 'Alimentação'), ('TRAVEL', 'Viagens'), ('CULTURE_ART', 'Cultura e Arte'), ('POLITICS_SOCIAL', 'Política e Sociedade'), ('SCIENCE_EDUCATION', 'Ciência e Educação'), ('FASHION_BEAUTY', 'Moda e Beleza'), ('OTHER', 'Outros')], default='OTHER', max_length=255),
        ),
    ]
